### PR TITLE
Add interface to allow systems to declare parameters

### PR DESCRIPTION
**Pull request by ivanpauno**
# 🎉 New feature

Based on https://github.com/ignitionrobotics/ign-transport/pull/305.
Replacement of https://github.com/ignitionrobotics/ign-gazebo/pull/1280.

## Summary

This PR adds:

- An interface that can be implemented by systems that allows them to declare parameters (`ISystemConfigureParameters`):
  - The gazebo simulation runner creates an instance of `ignition::transport::parameters::ParametersRegistry` (see https://github.com/ignitionrobotics/ign-transport/pull/305) with a namespace `/world/<world_name>` that provides the following services:
  - `/world/<world_name>/list_parameters` service: List available parameters names and types.
  - `/world/<world_name>/get_parameter` service: Get the type and value of a parameter.
  - `/world/<world_name>/set_parameter` service: Set a parameter: parameter name, value and type need to be provided.

Summary of what's needed to declare and use a parameter can be seen in the wheel slip demo [branch](https://github.com/ignitionrobotics/ign-gazebo/tree/ivanpauno/parameters-component-wheel-slip-demo6): [diff](https://github.com/ignitionrobotics/ign-gazebo/compare/b7b290cfd1e6984f66216bc1434a4df697844fd7..317f44880c837c7e887fcc35858a1b165e2bfb77).

## Test it

I haven't written automated tests yet, but there's a demo using parameters in the wheel slip plugin:

- https://github.com/ignitionrobotics/ign-gazebo/tree/ivanpauno/parameters-component-wheel-slip-demo6
- https://github.com/ignitionrobotics/ign-msgs/tree/ivanpauno/parameters-component-wheel-slip-demo8

Steps to run the demo:

- Build from source ignition `fortress` checking out the two branches specified above (I can provide PRs for another version if needed).
- Launch the trisphere cycle world:
  ```
  ign gazebo trisphere_cycle_wheel_slip.sdf
  ```
- In another terminal with the workspace sourced:
  - List available parameters:
    ```
    ign param -r /world/wheel_slip -l
    ```
    <details>
      <summary>Expected output</summary>

      > systems.wheel_slip.trisphere_cycle1.wheel_front            [ignition.msgs.WheelSlipParameters]
      > systems.wheel_slip.trisphere_cycle1.wheel_rear_right            [ignition.msgs.WheelSlipParameters]
      > systems.wheel_slip.trisphere_cycle0.wheel_rear_right            [ignition.msgs.WheelSlipParameters]
      > systems.wheel_slip.trisphere_cycle1.wheel_rear_left            [ignition.msgs.WheelSlipParameters]
      > systems.wheel_slip.trisphere_cycle0.wheel_rear_left            [ignition.msgs.WheelSlipParameters]
      > systems.wheel_slip.trisphere_cycle0.wheel_front            [ignition.msgs.WheelSlipParameters]

    </details>
  - Get the `systems.wheel_slip.trisphere_cycle1.wheel_front` parameter:
    ```
    ign param -r /world/wheel_slip -g -n systems.wheel_slip.trisphere_cycle1.wheel_front
    ```
    <details>
      <summary>Expected output</summary>

      >
      > Getting parameter [systems.wheel_slip.trisphere_cycle1.wheel_front] for registry namespace [/world/wheel_slip]...
      > Parameter type [ign_msgs.WheelSlipParameters]
      >
      > ------------------------------------------------
      > slip_compliance_lateral: 1
      > slip_compliance_longitudinal: 1
      > ------------------------------------------------

    </details>
  - Set the `systems.wheel_slip.trisphere_cycle1.wheel_front` parameter to a different value:
    ```
    ign param -r /world/wheel_slip -s -n systems.wheel_slip.trisphere_cycle1.wheel_front -t ign_msgs.WheelSlipParameters -m "
      slip_compliance_lateral: 1
      slip_compliance_longitudinal: 2"
    ```
    <details>
      <summary>Expected output</summary>

      >
      > Setting parameter [systems.wheel_slip.trisphere_cycle1.wheel_front] for world [wheel_slip]...
      >
      > Parameter successfully set!

    </details>
  - Get the `systems.wheel_slip.trisphere_cycle1.wheel_front` parameter again, its value should have changed:
    ```
    ign param -r /world/wheel_slip -g -n systems.wheel_slip.trisphere_cycle1.wheel_front
    ```
    <details>
      <summary>Expected output</summary>

      >
      > Getting parameter [systems.wheel_slip.trisphere_cycle1.wheel_front] for registry namespace [/world/wheel_slip]...
      > Parameter type [ign_msgs.WheelSlipParameters]
      >
      > ------------------------------------------------
      > slip_compliance_lateral: 1
      > slip_compliance_longitudinal: 2
      > ------------------------------------------------

    </details>

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
I've made a prerelease of gz-transport11, so macOS and windows CI is unstable, but Ubuntu will need some extra work for CI to pass. I think this is ready for review

**Comment by ivanpauno** [comment]
@scpeters I have rebased the PR.

> I think this is ready for review

Yes!
Let me know if I should add any reviewer here

**Comment by mjcarroll** [comment]
I think there are still some linter issues here.

**Comment by ivanpauno** [comment]
> I think there are still some linter issues here.

Could you share in which job you are seeing the failures?
It seems to me that all jobs are failing when building, because the gz-transport changes needed haven't been released yet.
I didn't find linters failures in the jobs' output.
Locally, I also don't see linter failures (though I'm not sure if I have cppcheck configured correctly, as I see a lot of unrelated linter errors).

**Comment by scpeters** [comment]
testing against prerelease of ignition-transport11 with https://github.com/gazebosim/gz-sim/pull/1789

**Comment by ivanpauno** [comment]
Thanks Steve!
Failures look unrelated to me, let me know if that's not the case.

I think this is ready for review.

**Review by adityapande-1995 — APPROVED** [review]
Is there a way you could add any tests for these ? Otherwise looks good.

**Comment by ivanpauno** [comment]
> Is there a way you could add any tests for these ? Otherwise looks good.

I think I can add some test, I will try to do that in the following days.

**Comment by scpeters** [comment]
> This needs a (not-prerelease) transport11 release. Is there anything blocking that at this point?

just the principle of testing with prereleases before we lock in new APIs. I'll open a `ci_matching_branch/` PR  to test with prereleases

**Comment by scpeters** [comment]
> > This needs a (not-prerelease) transport11 release. Is there anything blocking that at this point?
> 
> just the principle of testing with prereleases before we lock in new APIs. I'll open a `ci_matching_branch/` PR to test with prereleases

I forgot I had already done that with #1789. The Ubuntu CI is building fine but failing with some test failures

**Review by adityapande-1995 — CHANGES_REQUESTED** [review]
Test looks good, but CI is failing with : 
```
 /github/workspace/include/ignition/gazebo/System.hh:28:10: fatal error: ignition/transport/parameters/Registry.hh: No such file or directory
   #include <ignition/transport/parameters/Registry.hh>
```

Changes here look good to me, waiting for green CI.

**Comment by scpeters** [comment]
> Test looks good, but CI is failing with :
> 
> ```
>  /github/workspace/include/ignition/gazebo/System.hh:28:10: fatal error: ignition/transport/parameters/Registry.hh: No such file or directory
>    #include <ignition/transport/parameters/Registry.hh>
> ```
> 
> Changes here look good to me, waiting for green CI.

I think this was working with the 11.3.0~pre1 prerelease, but it is not working with the 11.3.0 or 11.3.1 stable releases. Investigating...

**Comment by scpeters** [comment]
> I think this was working with the 11.3.0~pre1 prerelease, but it is not working with the 11.3.0 or 11.3.1 stable releases. Investigating...

I think https://github.com/gazebosim/gz-transport/pull/374 should fix it, though it will require another release

**Review by adityapande-1995 — COMMENTED** [review]
A question for @ivanpauno , is this meant to be used by sensors (or their systems) ? Right now for the wheel slip plugin I can understand that there will be only a single system, but in future if some sensor wants to declare parameters, how should the system separate parameters between sensors ?

For e.g., camera 1 and camera 2 want to have different parameters in the rendering sensors system ? Maybe this is not the intended use case.

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
there's a few jobs with failing tests, but there are some clean CI jobs as well

**Comment by ivanpauno** [comment]
> A question for @ivanpauno , is this meant to be used by sensors (or their systems) ? Right now for the wheel slip plugin I can understand that there will be only a single system, but in future if some sensor wants to declare parameters, how should the system separate parameters between sensors ?
>
> For e.g., camera 1 and camera 2 want to have different parameters in the rendering sensors system ? Maybe this is not the intended use case.

My idea is that the system is responsible of correct naming.
My branch with a wheel slip plugin demo is out of date, but it still gives an idea of how to avoid name colisions:

https://github.com/gazebosim/gz-sim/blob/c7ca5a33a450533223908b08b9a18d9ab5d1f723/src/systems/wheel_slip/WheelSlip.cc#L380-L389

e.g. for cameras it could be:

```
/systems/sensors/cameras/camera1/<param_name>
```

**Comment by ivanpauno** [comment]
> I think https://github.com/gazebosim/gz-transport/pull/374 should fix it, though it will require another release

Thanks for the fix @scpeters !!!

> there's a few jobs with failing tests, but there are some clean CI jobs as well

I have taken a look to the failing jobs and they seem to have unrelated failures.
Let me know if any change is needed here.

**Review by adityapande-1995 — APPROVED** [review]
LGTM

**Review by azeey — APPROVED** [review]
LGTM!
